[package]
name = "wlang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substring = "1.4.5"
phf = { version = "0.10.1", features = ["macros"] }
regex = "1.5.4"
lazy_static = "1.4.0"
